name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test
